### ISSUE TITLE
Can't use certificates with pass phrases

### ISSUE THREAD

**Issue by johnpletka** [contentauth/c2pa-python#14]
I don't see any way to include a password for signing certificates.  For example:
```
 sign_info = c2pa.SignerInfo("es256",
                                        cert_file.read(),
                                        key_file.read(),
                                        "http://timestamp.digicert.com")
```
I get prompted at the CMD line for "Enter PEM pass phrase:", but this needs to run headless without user interaction.  Is there a way to supply the pass phrase to the SignerInfo?  Or any other work around?

**Comment by gpeacock** [comment]
You have to extract the keys on your own before handing them to us.
