### ISSUE TITLE
Is Key Usage Extension emailProtection a must?

### ISSUE THREAD

**Issue by ttbuffey** [contentauth/c2pa-python#51]
for the certificate required by c2pa, is Is Key Usage Extension **emailProtection** a must? what if we don't include it.

**Comment by crandmck** [comment]
Yes, either that or document signing EKU, as explained in the documentation: https://opensource.contentauthenticity.org/docs/prod-cert#purchasing-a-certificate.

See also https://opensource.contentauthenticity.org/docs/manifest/signing-manifests#certificates.

**Comment by crandmck** [comment]
Closed as a question, not an actual bug or issue in the repo.
